set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_OSX_ARCHITECTURES arm64)

set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
if(PORT MATCHES "shader-slang")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
elseif(PORT MATCHES "dbus")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
#set(VCPKG_OSX_SYSROOT($ENV{MACOS_SDK_PATH}))

set(VCPKG_FIXUP_ELF_RPATH ON)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/toolchains/clang-toolchain.cmake)
