set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_VISUAL_STUDIO_PATH $ENV{VISUAL_STUDIO_PATH})

set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_ENV_PASSTHROUGH LLVM_ROOT PATH)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/../toolchains/clang.toolchain.cmake)
