set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_VISUAL_STUDIO_PATH $ENV{VISUAL_STUDIO_PATH})

set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_BUILD_TYPE release)

set(
	VCPKG_ENV_PASSTHROUGH
		PATH
		FASTBUILD_BROKERAGE_PATH
		FASTBUILD_CACHE_PATH
		FASTBUILD_CACHE_MODE
)
set(
	VCPKG_CMAKE_CONFIGURE_OPTIONS
		#-DCMAKE_GENERATOR=FASTBuild 
		#-DCMAKE_GENERATOR_TOOLSET=ClangCL -- only works with Visual Studio Generators
		-DCMAKE_C_COMPILER=clang-cl
		-DCMAKE_CXX_COMPILER=clang-cl
		-DLIBCXX_ENABLE_SHARED=OFF
		-DLIBCXX_ENABLE_STATIC=ON
)
set(VCPKG_DISABLE_COMPILER_TRACKING ON)
