cmake_minimum_required(VERSION 3.21)

include_guard()

#set(LLVM_PATH $ENV{LLVM_PATH} CACHE PATH "LLVM root path")
set(LLVM_PATH "C:\\Program Files\\LLVM" CACHE PATH "LLVM root path")

#message(NOTICE ${LLVM_PATH})

#set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES "CMAKE_SYSTEM_PROCESSOR;CMAKE_CROSSCOMPILING")
#set(CMAKE_CROSSCOMPILING TRUE)

if(WIN32)
	set(CMAKE_EXECUTABLE_SUFFIX ".exe")
endif()

set(CMAKE_C_COMPILER ${LLVM_PATH}/bin/clang${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_CXX_COMPILER ${LLVM_PATH}/bin/clang++${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_RC_COMPILER ${LLVM_PATH}/bin/llvm-rc${CMAKE_EXECUTABLE_SUFFIX})

set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

#set(CMAKE_C_EXTENSIONS OFF)
#set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_C_STANDARD 23)
set(CMAKE_CXX_STANDARD 23)

#set(CMAKE_C_FLAGS "")
#set(CMAKE_CXX_FLAGS "")

set(CMAKE_C_COMPILER_FRONTEND_VARIANT "GNU")
set(CMAKE_CXX_COMPILER_FRONTEND_VARIANT "GNU")

#set(CMAKE_VERBOSE_MAKEFILE ON)
