set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)

if (VCPKG_TARGET_IS_WINDOWS)
	set(FASTBUILD_EXE_SUFFIX ".exe")
	vcpkg_download_distfile(
		ARCHIVE
		URLS "https://github.com/djohansson/fastbuild/releases/download/v${VERSION}/FASTBuild-Windows-x64-v${VERSION}-djohansson.zip"
		FILENAME "FASTBuild-Windows-x64-v${VERSION}-djohansson.zip"
		SHA512 57FFB427EDF0ACBBD51DD76C5FC7E2F9E1802BA8EAF64BB4AC4E365E776D3F1CEDC740D3281B3075AF548B86B38955DA18577B7907FC12D708BCB9408DE3B79B
	)
endif()

vcpkg_extract_source_archive(
	BINDIST_PATH
	ARCHIVE "${ARCHIVE}"
	NO_REMOVE_ONE_LEVEL
)

file(INSTALL "${BINDIST_PATH}/FBuild${FASTBUILD_EXE_SUFFIX}" DESTINATION "${CURRENT_PACKAGES_DIR}/tools/${PORT}")
file(INSTALL "${BINDIST_PATH}/FBuildWorker${FASTBUILD_EXE_SUFFIX}" DESTINATION "${CURRENT_PACKAGES_DIR}/tools/${PORT}")
file(INSTALL "${BINDIST_PATH}/LICENSE.TXT" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
