cmake_minimum_required(VERSION 3.21)

include_guard()

set(LLVM_PATH $ENV{LLVM_PATH} CACHE PATH "LLVM root path")
set(LLVM_VERSION_MAJOR $ENV{LLVM_VERSION_MAJOR} CACHE PATH "LLVM major version")
set(TARGET_ARCHITECTURE $ENV{TARGET_ARCHITECTURE} CACHE PATH "Target architecture")

if(NOT (DEFINED ${CMAKE_CROSSCOMPILING} AND ${CMAKE_CROSSCOMPILING}))
	if (NOT DEFINED ${CMAKE_SYSTEM_PROCESSOR})
		set(CMAKE_SYSTEM_PROCESSOR ${CMAKE_HOST_SYSTEM_PROCESSOR})
	endif()
	if (NOT DEFINED ${CMAKE_SYSTEM_NAME})
		set(CMAKE_SYSTEM_NAME ${CMAKE_HOST_SYSTEM_NAME})
	endif()
	if (NOT DEFINED ${CMAKE_SYSTEM_VERSION})
		set(CMAKE_SYSTEM_VERSION ${CMAKE_HOST_SYSTEM_VERSION})
	endif()
endif()


if(CMAKE_SYSTEM_NAME MATCHES "Windows")
	set(CMAKE_EXECUTABLE_SUFFIX ".exe")
else()
	set(CMAKE_EXECUTABLE_SUFFIX "")
endif()

set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES "CMAKE_SYSTEM_PROCESSOR;CMAKE_SYSTEM_NAME;CMAKE_SYSTEM_VERSION")

set(CMAKE_AR ${LLVM_PATH}/bin/llvm-ar${CMAKE_EXECUTABLE_SUFFIX})

set(CMAKE_C_COMPILER ${LLVM_PATH}/bin/clang${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_C_COMPILER_ID "Clang")
set(CMAKE_C_COMPILER_FRONTEND_VARIANT "GNU")

set(CMAKE_CXX_COMPILER ${LLVM_PATH}/bin/clang++${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_CXX_COMPILER_ID "Clang")
set(CMAKE_CXX_COMPILER_FRONTEND_VARIANT "GNU")

#set(CMAKE_LINKER_TYPE "LLD") # no effect?

set(CMAKE_RC_COMPILER ${LLVM_PATH}/bin/llvm-rc${CMAKE_EXECUTABLE_SUFFIX})

set(CMAKE_C_STANDARD 23)
set(CMAKE_CXX_STANDARD 23)

set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_C_EXTENSIONS OFF)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_C_EXCEPTIONS OFF)
set(CMAKE_CXX_EXCEPTIONS OFF)

set(CMAKE_C_RTTI OFF)
set(CMAKE_CXX_RTTI OFF)

set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

set(CLANG_COMMON_FLAGS "")
if (CMAKE_SYSTEM_PROCESSOR MATCHES "arm.*|aarch64")
	set(CLANG_COMMON_FLAGS "${CLANG_COMMON_FLAGS} -march=native+crc+crypto")
else()
	set(CLANG_COMMON_FLAGS "${CLANG_COMMON_FLAGS} -march=native")
endif()
set(CLANG_COMMON_FLAGS_RELEASE "")
set(CLANG_C_FLAGS "")
set(CLANG_CXX_FLAGS "-stdlib=libc++")
set(LINK_COMMON_FLAGS "-fuse-ld=lld -lc++ -lc++abi")

if(CMAKE_SYSTEM_NAME MATCHES "Windows")
	set(CLANG_COMMON_FLAGS "${CLANG_COMMON_FLAGS} -gcodeview -Xclang -cfguard")
	set(CLANG_COMMON_FLAGS_RELEASE "-flto")
elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
	set(CLANG_C_FLAGS "${CLANG_C_FLAGS} -D_GNU_SOURCE")
	set(LINK_COMMON_FLAGS "${LINK_COMMON_FLAGS} -Wl,--undefined-version")
endif()

set(CMAKE_C_FLAGS "${CLANG_COMMON_FLAGS} ${CLANG_C_FLAGS}")
set(CMAKE_C_FLAGS_DEBUG "-O0 -g -D_DEBUG -fno-omit-frame-pointer")
set(CMAKE_C_FLAGS_RELEASE "${CLANG_COMMON_FLAGS_RELEASE} -O3 -g -DNDEBUG")
set(CMAKE_CXX_FLAGS "${CLANG_COMMON_FLAGS} ${CLANG_CXX_FLAGS}")
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g -D_DEBUG -fno-omit-frame-pointer")
set(CMAKE_CXX_FLAGS_RELEASE "${CLANG_COMMON_FLAGS_RELEASE} -O3 -g -DNDEBUG")

set(CMAKE_EXE_LINKER_FLAGS "${LINK_COMMON_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS "${LINK_COMMON_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${LINK_COMMON_FLAGS}")
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)

#set(CMAKE_VERBOSE_MAKEFILE ON)
